//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumidorServicioWeb.WServicioWebReporteFactura {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WServicioWebReporteFactura.wsReporteSoap")]
    public interface wsReporteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reporteFactura", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet reporteFactura();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reporteFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> reporteFacturaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsReporteSoapChannel : ConsumidorServicioWeb.WServicioWebReporteFactura.wsReporteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsReporteSoapClient : System.ServiceModel.ClientBase<ConsumidorServicioWeb.WServicioWebReporteFactura.wsReporteSoap>, ConsumidorServicioWeb.WServicioWebReporteFactura.wsReporteSoap {
        
        public wsReporteSoapClient() {
        }
        
        public wsReporteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsReporteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsReporteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsReporteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet reporteFactura() {
            return base.Channel.reporteFactura();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> reporteFacturaAsync() {
            return base.Channel.reporteFacturaAsync();
        }
    }
}
