//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumidorServicioWeb.WServicioWebFormaPago {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WServicioWebFormaPago.wsFormaPagoSoap")]
    public interface wsFormaPagoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/formas_pago", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet formas_pago();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/formas_pago", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> formas_pagoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_formaPago", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertar_formaPago(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_formaPago", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertar_formaPagoAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_formaPago", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int eliminar_formaPago(int idFormaPago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_formaPago", ReplyAction="*")]
        System.Threading.Tasks.Task<int> eliminar_formaPagoAsync(int idFormaPago);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsFormaPagoSoapChannel : ConsumidorServicioWeb.WServicioWebFormaPago.wsFormaPagoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsFormaPagoSoapClient : System.ServiceModel.ClientBase<ConsumidorServicioWeb.WServicioWebFormaPago.wsFormaPagoSoap>, ConsumidorServicioWeb.WServicioWebFormaPago.wsFormaPagoSoap {
        
        public wsFormaPagoSoapClient() {
        }
        
        public wsFormaPagoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsFormaPagoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsFormaPagoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsFormaPagoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet formas_pago() {
            return base.Channel.formas_pago();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> formas_pagoAsync() {
            return base.Channel.formas_pagoAsync();
        }
        
        public int insertar_formaPago(string nombre) {
            return base.Channel.insertar_formaPago(nombre);
        }
        
        public System.Threading.Tasks.Task<int> insertar_formaPagoAsync(string nombre) {
            return base.Channel.insertar_formaPagoAsync(nombre);
        }
        
        public int eliminar_formaPago(int idFormaPago) {
            return base.Channel.eliminar_formaPago(idFormaPago);
        }
        
        public System.Threading.Tasks.Task<int> eliminar_formaPagoAsync(int idFormaPago) {
            return base.Channel.eliminar_formaPagoAsync(idFormaPago);
        }
    }
}
