//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumidorServicioWeb.WServicioWebReporteVentas {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WServicioWebReporteVentas.wsReporteVentasSoap")]
    public interface wsReporteVentasSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reporteVenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet reporteVenta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reporteVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> reporteVentaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsReporteVentasSoapChannel : ConsumidorServicioWeb.WServicioWebReporteVentas.wsReporteVentasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsReporteVentasSoapClient : System.ServiceModel.ClientBase<ConsumidorServicioWeb.WServicioWebReporteVentas.wsReporteVentasSoap>, ConsumidorServicioWeb.WServicioWebReporteVentas.wsReporteVentasSoap {
        
        public wsReporteVentasSoapClient() {
        }
        
        public wsReporteVentasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsReporteVentasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsReporteVentasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsReporteVentasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet reporteVenta() {
            return base.Channel.reporteVenta();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> reporteVentaAsync() {
            return base.Channel.reporteVentaAsync();
        }
    }
}
