//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumidorServicioWeb.WServicioWebTipoGasolina {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WServicioWebTipoGasolina.wsTipoGasolinaSoap")]
    public interface wsTipoGasolinaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/precios_gasolina", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet precios_gasolina();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/precios_gasolina", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> precios_gasolinaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/tipoGas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet tipoGas(int idTipoGas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/tipoGas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> tipoGasAsync(int idTipoGas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_tipoGas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int actualizar_tipoGas(int idTipoGas, string nombre, double precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_tipoGas", ReplyAction="*")]
        System.Threading.Tasks.Task<int> actualizar_tipoGasAsync(int idTipoGas, string nombre, double precio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsTipoGasolinaSoapChannel : ConsumidorServicioWeb.WServicioWebTipoGasolina.wsTipoGasolinaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsTipoGasolinaSoapClient : System.ServiceModel.ClientBase<ConsumidorServicioWeb.WServicioWebTipoGasolina.wsTipoGasolinaSoap>, ConsumidorServicioWeb.WServicioWebTipoGasolina.wsTipoGasolinaSoap {
        
        public wsTipoGasolinaSoapClient() {
        }
        
        public wsTipoGasolinaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsTipoGasolinaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsTipoGasolinaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsTipoGasolinaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet precios_gasolina() {
            return base.Channel.precios_gasolina();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> precios_gasolinaAsync() {
            return base.Channel.precios_gasolinaAsync();
        }
        
        public System.Data.DataSet tipoGas(int idTipoGas) {
            return base.Channel.tipoGas(idTipoGas);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> tipoGasAsync(int idTipoGas) {
            return base.Channel.tipoGasAsync(idTipoGas);
        }
        
        public int actualizar_tipoGas(int idTipoGas, string nombre, double precio) {
            return base.Channel.actualizar_tipoGas(idTipoGas, nombre, precio);
        }
        
        public System.Threading.Tasks.Task<int> actualizar_tipoGasAsync(int idTipoGas, string nombre, double precio) {
            return base.Channel.actualizar_tipoGasAsync(idTipoGas, nombre, precio);
        }
    }
}
